### ISSUE TITLE
Error while training, feature file not found

### ISSUE THREAD

**Issue by DivyaWadehra** [prdwb/bert_hae#1]
TypeError: convert_examples_to_variations_and_then_features() missing 2 required positional arguments: 'glove' and 'tfidf_vectorizer'

**Comment by prdwb** [comment]
Hi, these arguments were for early explorations and were not used in the paper. We didn't catch this error because we experimented with feature files that were already generated. Sorry for the inconvenience.

A quick fix is to remove the code related to glove and tfidf. I will fix this as soon as possible. Also feel free to create a pull request. Thanks.

**Comment by prdwb** [comment]
Hi, it's fixed. thanks.

**Comment by DivyaWadehra** [comment]
Thanks :)
