### ISSUE TITLE
about FLAGS.history

### ISSUE THREAD

**Issue by berton820** [prdwb/bert_hae#3]
why you comment out FLAGS.history, and what's the different between FLAGS.history and FLAGS.max_considered_history_turns 
https://github.com/prdwb/bert_hae/blob/f9cf5d79be949cea516624ba91a142cfabe39d2b/cqa_supports.py#L142

**Comment by prdwb** [comment]
Sorry for the confusions. The line is commented because the start index is set in line 149. It's always set to 0, meaning that we read in all history turns. Then during preprocessing, the number of history turns we want to include in the processed features are set to FLAGS.max_considered_history_turns. During training, we decide how many turns we really want to incorporate in the model, which is set to FLAGS.history.

**Comment by berton820** [comment]
If I'm sure FLAGS.history equals 4, as long as the FLAGS.max_considered_history_turns is greater than 4, it will be ok？（ That means the result should be same whatever FLAGS.max_considered_history_turns==4 or 11, right?）

**Comment by prdwb** [comment]
I believe so. But I only experimented with FLAGS.max_considered_history_turns set to 11. Thanks.

**Comment by berton820** [comment]
make sense ,Thanks a million ~
