### ISSUE TITLE
Error can not find train_summay

### ISSUE THREAD

**Issue by WenTingTseng** [prdwb/bert_hae#5]
<img width="655" alt="擷取" src="https://user-images.githubusercontent.com/32416416/71244140-cb172600-234c-11ea-813b-50f9c6ecbb8f.PNG">
When I run the code hae.py in line 263 to 270. Why it always run to except block? So when it in the line 272 "train_summary_writer.add_summary(train_summary, step)" it can not find "train_summary"

How can I fix it? thanks a lot

**Comment by prdwb** [comment]
It seems that the training step fails, probably due to an empty feed dict. What is the length printed in the exception? Could you attach the running log? Thanks.

**Comment by WenTingTseng** [comment]
Features length printed in the exception is 6.
And I run the code hae.py like this
<img width="292" alt="444" src="https://user-images.githubusercontent.com/32416416/71262763-6de69900-237b-11ea-8f00-08e81938be4e.PNG">
And the running log like this
<img width="960" alt="333" src="https://user-images.githubusercontent.com/32416416/71263293-991db800-237c-11ea-929c-f66ca42ac689.PNG">

due to an empty feed dict?Which dict?Is cache/quac?
My cache/quac dict like this
<img width="188" alt="555" src="https://user-images.githubusercontent.com/32416416/71263081-27456e80-237c-11ea-9031-18af709fb86b.PNG">

Thanks for your respond

**Comment by prdwb** [comment]
Hi, thank you for your snapshots. It seems that you have a "resource exhausted (out of memory)" error, probably because you are running on a CPU. This should be the reason that a training step fails. If you could refer to the following snapshot. Using a smaller batch size should resolve the issue. Note that a smaller batch size could hurt the performance. 

![image](https://user-images.githubusercontent.com/12870484/71263277-99cc3500-230f-11ea-9a94-48554f226114.png)

I can see cache/quac is correctly generated. There is no issue with that. Thanks.

**Comment by WenTingTseng** [comment]
Hi, thank you for your respond.I change train_batch_size to 1 but it has problem like the log message
<img width="959" alt="666" src="https://user-images.githubusercontent.com/32416416/71267314-3d0b6180-2385-11ea-98b7-90da99a21e57.PNG">
It seems that "resource exhausted (out of memory)" error cause the problem.(no sure)
How can resolve it . If I run the code on GPU.But how can change to run on gpu?
Thanks a lot

**Comment by prdwb** [comment]
It seems that the process was killed by the system without an error. So I agree that it could be due to memory issues. Using a smaller max_seq_length should further alleviate memory consumption but it will hurt the performance. 

GPU usage will be handled by TensorFlow automatically, assuming you have set up the CUDA environment and installed the GPU version of TensorFlow. There is no need to modify the code. Thank you.
